
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d66fd12994'
down_revision: Union[str, None] = 'c1881ecb9503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('class_teacher_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'classes', ['class_teacher_id'])
    op.create_foreign_key(None, 'classes', 'teachers', ['class_teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_constraint(None, 'classes', type_='unique')
    op.drop_column('classes', 'class_teacher_id')
    # ### end Alembic commands ###